# @package habitat.task

defaults:
  - task_config_base
  - actions:
    - stop
    - move_forward
    - turn_left
    - turn_right
  - measurements:
    - top_down_map
    - exploration_vlr
    - exploration_success
  - lab_sensors:
    - pointgoal_with_gps_compass_sensor
  - _self_

type: Nav-v0
end_on_success: True
reward_measure: "exploration_vlr"
success_measure: "exploration_success"
goal_sensor_uuid: pointgoal_with_gps_compass
measurements:
  top_down_map:
    map_padding: 0
    map_resolution: 1024
    meters_per_pixel: 0.25 # if meters_per_pixel is set, map_resolution is ignored
    draw_source: False
    draw_border: False
    draw_shortest_path: False
    draw_view_points: False
    draw_goal_positions: False
    draw_goal_aabbs: False
    fog_of_war:
      draw: True
      visibility_dist: 5.0 # meters
      fov: 90
  exploration_vlr:
    alpha: 1.0
  exploration_success:
    success_threshold: 0.7
