# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: exploration_task
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: agent_base  # agent_base depth_agent rgb_agent rgbd_agent
  - /habitat/task/lab_sensors:
    - pointgoal_with_gps_compass_sensor
  - /habitat/dataset: dataset_config_schema
  - _self_

habitat:
  seed: 1
  env_task: GymHabitatEnv
  environment:
    max_episode_steps: 300
    iterator_options:
      group_by_scene: True
      num_episode_sample: 1
      shuffle: True
      cycle: True
  simulator:
    habitat_sim_v0:
      gpu_device_id: 0

  dataset:
    type: ExplorationStaticDataset
    split: train_10_percent
    data_path: data/datasets/exploration/hm3d/v1/{split}/{split}.json.gz
    content_scenes:
      - 5Poh4Qz68hd